# Lab 3

## Step 1

In [2]:
pip install tensorflow


   ---------------------------------------- 0.0/331.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/331.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/331.9 MB 1.5 MB/s eta 0:03:38
   ---------------------------------------- 1.0/331.9 MB 1.8 MB/s eta 0:03:04
   ---------------------------------------- 1.3/331.9 MB 1.8 MB/s eta 0:03:08
   ---------------------------------------- 1.8/331.9 MB 1.9 MB/s eta 0:02:54
   ---------------------------------------- 2.1/331.9 MB 1.9 MB/s eta 0:02:52
   ---------------------------------------- 2.6/331.9 MB 1.9 MB/s eta 0:02:51
   ---------------------------------------- 2.9/331.9 MB 2.0 MB/s eta 0:02:49
   ---------------------------------------- 3.4/331.9 MB 1.9 MB/s eta 0:02:55
   ---------------------------------------- 3.4/331.9 MB 1.9 MB/s eta 0:02:55
   ---------------------------------------- 3.7/331.9 MB 1.7 MB/s eta 0:03:12
    --------------------------------------- 4.2/331.9 MB 1.7 MB/s eta 0:03:12

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.37.1 requires protobuf<6,>=3.20, but you have protobuf 6.33.1 which is incompatible.


In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Step 2

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


## Step 3

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## Step 4

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Step 5

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Step 6

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Make ANN Model

## Step 1

In [13]:
ann = tf.keras.models.Sequential()

## Step 2

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Step 3

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Step 4

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training Model

## Step 1

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Step 2

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 910us/step - accuracy: 0.7345 - loss: 0.5809
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8067 - loss: 0.4632
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8173 - loss: 0.4372
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8210 - loss: 0.4268
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.8265 - loss: 0.4170
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8291 - loss: 0.4068  
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.8331 - loss: 0.3978
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8351 - loss: 0.3909
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8375 - loss: 0.3860
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8405 - loss: 0.3815
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8416 - loss: 0.3772
Epoch 12/100
250/250 

# Predict

## New Model

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
[[False]]


## Predict

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Accuracy and Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1534   61]
 [ 206  199]]


0.8665